#%RAML 1.0
title: Donnees de contrevenant alimentaire a Montreal
types:
  Contrevenant:
    type: object
    properties:
      id:
        type: integer
        required: true
      adresse:
        type: string
        required: true
      categorie:
        type: string
        required: true
      date_infraction:
        type: string
        required: true
      date_jugement:
        type: string
        required: true
      description:
        type: string
        required: true
      etablissement:
        type: string
        required: true
      montant:
        type: number
        required: true
      proprietaire:
        type: string
        required: true
      ville:
        type: string
        required: true

  Infraction:
    type: object
    properties:
      date_infraction:
        type: string
        required: true
      montant:
        type: number
        required: true
      description:
        type: string
        required: true

  Infractions:
    type: Infraction
    uniqueItems: true

  Etablissement:
    type: object
    properties:
      name:
        type: string
        required: true
      nbinfractions:
        type: integer
        required: true
      infractions:
        type: Infractions
        required: false

/api:
  /contrevenant:
    get:
      description: Extraction des contrevenants entre deux dates en ISO avec parametres "du" et "au".
      responses:
        200:
          body:
            application/json:
              type: Contrevenant[]
        400:
          description: Invalid date format or paramater names
  /etablissement:
    get:
      description: Extraction des etablissements qui ont fait plus d'une infraction et montre le nombre des infractions selon le Content-Type(application/json,application/xml,text/csv). OBLIGÉ D'AVOIR SET Content-Type DANS LE HEADER!
      responses:
        200:
          body:
            application/json:
              type: Etablissement[]	
            application/xml:
              type: Etablissement[]
            text/csv:
              type: Etablissement[]
        400:
          description: Invalid or no Content-Type specified